# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd7301de0bb884db88c9ee41a7fcedf76fb1d3ee852b8ecb2228769788ed2c1371e6488f627c4b52438870aad8e6b7f87b7d070702e48048deeba165f32eae18

test:
  secret_key_base: 07b32bae4a0103f720bdcab5149e31b58f7bd76bc421a4318f26d1fae5a6110d55acb01b99a85df679150e1f5324eaab39ced22f14b7c27369ccdd118007c675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
